### ISSUE TITLE
Transaction signature

### ISSUE THREAD

**Issue by Abhishek-1857** [hyperledger/solang#1009]
How can i get the transaction hash or signature for the function im calling of the solidity contract for solana

Libraries im using is solana web3 and solana solana solidity

here's the code :
    const contract = new Contract(connection, program.publicKey, storage.publicKey, ERC20_ABI, payer)  
   const to="xyz"
   const transaction =await contract.functions.burnSolana2Gxt(to, 1) 
console.log(transaction.hash); // or anything for getting signature or hash

**Comment by Abhishek1857** [comment]
Any idea on how to get transaction signature for contract function written in solidity

**Comment by xermicus** [comment]
Hi there! How is this issue related to solang? Are you only unable to get the transaction hash for Contracts compiled with solang, or in general?

**Comment by seanyoung** [comment]
The `@solana/solidity` library does not return the transaction signature. I've added this here: https://github.com/solana-labs/solana-solidity.js/pull/39 

Let me know what you think @Abhishek-1857

**Comment by Abhishek1857** [comment]
> 

Yes its related to solang. Yes i can't get the hash for contracts compiled with solang and the contract is written in solidity

**Comment by seanyoung** [comment]
@Abhishek1857 this should be resolved now. For now this requires using `@solana/solidity` from git: https://github.com/solana-labs/solana-solidity.js/pull/39

Please let us know if this works for you, thanks
