### ISSUE TITLE
Solang compile error

### ISSUE THREAD

**Issue by Purva-Chaudhari** [hyperledger/solang#1014]
Hi , I installed solang on my mac using the brew command (`brew install hyperledger/solang/solang`). 
When i try to run `solang compile --target solana flipper.sol` I get the following error:
```
error: file not found 'compile'

warning: 'public': visibility for constructors is ignored
  ┌─ /Users/purvachaudhari/Desktop/Kaleidoscope/solang/flipper.sol:4:30
  │
4 │     constructor(bool initvalue) public {
  │                                 ^^^^^^

error: not all contracts are valid
```
Any help with this?

**Comment by extraymond** [comment]
The version you're using doesn't require the compile subcommand, you can check it by `solang --help`
