### ISSUE TITLE
LLVM ERROR: Unsupported dynamic stack allocation on create_program_address with Solang 0.1.13

### ISSUE THREAD

**Issue by stanta** [hyperledger/solang#1019]
Got this  error on Solang 0.1.13, when tried to call

`address pda =  create_program_address (["TokenAccountXXX", "seed"], _token );`

This LLVM Error fires when compiling of file finishing.

**Comment by seanyoung** [comment]
@stanta can you give the full solidity source code please so we can reproduce the issue? Thanks!

**Comment by stanta** [comment]
@seanyoung exactly as pasted above. 
_token receives as constructor's argument from `  publicKeyToHex (mintPubkey), ` where
`mintPubkey =  spl.createMint (...) `,
createMint is  from   @solana/spl-token JSlib

**Comment by seanyoung** [comment]
Whole solidity source code please

**Comment by stanta** [comment]
Under NDA, sorry. Can I send to  private address?

**Comment by stanta** [comment]
Under NDA, sorry. Can I send to  private address?

**Comment by stanta** [comment]
Hi, @seanyoung! 
I sent file to sean [at] mess [dot] org as in your profile.

**Comment by stanta** [comment]
@seanyoung, Thank you for fast fixing! Where can I pull fixed version of Solang compiler?

**Comment by seanyoung** [comment]
You can use the latest container image:
```
docker pull ghcr.io/hyperledger/solang:latest
```
Or you can download a binary from the latest CI on the main https://github.com/hyperledger/solang/actions/runs/3121674351
These are debug builds so they're larger and slower.

**Comment by stanta** [comment]
@seanyoung compile error gone, thank you.
But systematically get error "0x1" from smart contract when call this: 
 `stableTokenAccount =  create_program_address (["stableTokenAccount", _seedstableTokenAccount], stableProgramID );`

**Comment by seanyoung** [comment]
> @seanyoung compile error gone, thank you. But systematically get error "0x1" from smart contract when call this: ` address stableTokenAccount = create_program_address (["stableTokenAccount", _seedstableTokenAccount], stableProgramID );`

Return value `0x01` indicates that the `sol_create_program_address()` system call returned an error. This can be for one of the following reasons:
- More than 16 seeds (you only have 2)
- One of the seeds is longer than 32 bytes (is `_seedstableTokenAccount` longer than that?)
- The calculated address falls on the ed25519 curve

See https://docs.solana.com/developing/programming-model/calling-between-programs#hash-based-generated-program-addresses

There is also the `find_program_address()` which automatically adds a bump value, to ensure that the calculated address does not fall on the curve https://solang.readthedocs.io/en/latest/targets/solana.html#builtin-try-find-program-address

**Comment by stanta** [comment]
OK, Thanks, I'll check.

**Comment by stanta** [comment]
Hi, @seanyoung !
generation of PDAs works fine, thank you!
But have two questions.
1st try_find_program_address returns an ether-like address as a string, and it is not easy to convert this to Pubkey as Solana wants. Have you any suggestions on how to do this more painless?
2nd and more complex. How do make cross-programs-invitations (CPIs, aka contract-to-contract calls in Ether) from PDAs? 
In Rust, it looks like there:  https://gist.github.com/PirosB3/64818603c4917dc22f725e6459bd90c0#file-transfer_and_close-rs-L35
How can we do the same in Solang? Have you any suggestions here too?

Sincerely, Stan.

**Comment by stanta** [comment]
Hi, @seanyoung !
Truing to solve problem, described above, found in docs [passing-seeds-with-external-calls-on-solana ](https://solang.readthedocs.io/en/latest/language/functions.html#passing-seeds-with-external-calls-on-solana )
Trying to implement this in SPL token library:
` function TransferWithSeed(
            address programID,
            address from, 
            address to, 
            address owner, 
            uint64 amount,
            bytes[] _seeds
            ) internal {

		bytes instr = new bytes(9);

		instr[0] = uint8(TokenInstruction.Transfer);

		instr.writeUint64LE(amount, 1);

		AccountMeta[3] metas = [
			AccountMeta({pubkey: from, is_writable: true, is_signer: false}),
			AccountMeta({pubkey: to, is_writable: true, is_signer: false}),
			AccountMeta({pubkey: owner, is_writable: true, is_signer: true})
		];

		tokenProgramId.call{accounts: metas, seeds: _seeds}(instr);
	}`
But got when compiling: 
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/emit/instructions.rs:804:53
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace...

any suggestions?
