### ISSUE TITLE
Thread 'main' panicked  error when compiling call with seeds

### ISSUE THREAD

**Issue by stanta** [hyperledger/solang#1028]
Hi, @seanyoung !
Trying to solve problem, described above, found in docs [passing-seeds-with-external-calls-on-solana ](https://solang.readthedocs.io/en/latest/language/functions.html#passing-seeds-with-external-calls-on-solana )
Trying to implement this in SPL token library:
`function TransferWithSeed(
            address programID,
            address from, 
            address to, 
            address owner, 
            uint64 amount,
            bytes[] _seeds
            ) internal {

		bytes instr = new bytes(9);
		instr[0] = uint8(TokenInstruction.Transfer);
		instr.writeUint64LE(amount, 1);

		AccountMeta[3] metas = [
			AccountMeta({pubkey: from, is_writable: true, is_signer: false}),
			AccountMeta({pubkey: to, is_writable: true, is_signer: false}),
			AccountMeta({pubkey: owner, is_writable: true, is_signer: true})
		];

		tokenProgramId.call{accounts: metas, seeds: _seeds}(instr);
	}`
But got when compiling: 
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/emit/instructions.rs:804:53
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace...

If this string removed, compiling finishing ok:
`tokenProgramId.call{accounts: metas, seeds: _seeds}(instr);`

any suggestions?

**Comment by seanyoung** [comment]
Hi @stanta 
Unfortunately we are working very hard to rebuild Solang compiled contract to be Anchor compatible. This means that some parts are broken right now, I am afraid. This includes CPI with accounts and seeds.

This is being refactored 1) To use borsh encoding and 2) To use accounts/seeds the way anchor does.

Hopefully we will have this fixed soon. The aim is to have this work done for breakpoint in November, but it may overrun.

**Comment by stanta** [comment]
@seanyoung any prognoses about time of ready?

**Comment by seanyoung** [comment]
This work is this milestone https://github.com/hyperledger/solang/milestone/1 more details are in #964 .

The plan is to get this working by Breakpoint for the beginning of November: https://solana.com/breakpoint However, the way things are going, we may overrun. This year for certain.

**Comment by seanyoung** [comment]
dup of #1433
