### ISSUE TITLE
Flipper example does not work

### ISSUE THREAD

**Issue by wolfflow** [hyperledger/solang#1071]
**Describe the bug**
Got the `TransactionError: invalid program argument` error while running 
`node flipper.js`[code](https://github.com/hyperledger/solang#build-for-solana),
 having [Flipper contract](https://github.com/hyperledger/solang/blob/main/examples/flipper.sol) compiled

**To Reproduce**
1. What ledger are you using, e.g. Solana or Substrate -- **Solana**
2. Provide both Solidity source and client code (e.g. TypeScript)
Client: [code](https://github.com/hyperledger/solang#build-for-solana)
Solidity:  [Flipper contract](https://github.com/hyperledger/solang/blob/main/examples/flipper.sol) compiled
3. Provide Solang version number (output of `solang --version`) `solang version v0.1.13`
3. What behavior are you seeing?
```
Connecting to your local Solana node ...
Airdropping SOL to a new wallet ...
Program deployment finished, deploying the flipper contract ...
/Users/xf/Work/mycompany/_research/crypto/solana-apps/solana-web3-app/solang-demo/node_modules/@solana/solidity/lib/logs.js:163
            ? new errors_1.TransactionError(failedMatch[2])
              ^

TransactionError: invalid program argument
    at parseTransactionError (/Users/xf/Work/mycompany/_research/crypto/solana-apps/solana-web3-app/solang-demo/node_modules/@solana/solidity/lib/logs.js:163:15)
    at /Users/xf/Work/mycompany/_research/crypto/solana-apps/solana-web3-app/solang-demo/node_modules/@solana/solidity/lib/logs.js:123:27
    at Generator.throw (<anonymous>)
    at rejected (/Users/xf/Work/mycompany/_research/crypto/solana-apps/solana-web3-app/solang-demo/node_modules/@solana/solidity/lib/logs.js:6:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  logs: [
    'Program 11111111111111111111111111111111 invoke [1]',
    'Program 11111111111111111111111111111111 success',
    'Program 45kKyo1nPXUd2cQQPm2kTHHxpRn7cmrRu2AkAyBPyJSx invoke [1]',
    'Program 45kKyo1nPXUd2cQQPm2kTHHxpRn7cmrRu2AkAyBPyJSx consumed 490 of 400000 compute units',
    'Program 45kKyo1nPXUd2cQQPm2kTHHxpRn7cmrRu2AkAyBPyJSx failed: invalid program argument'
  ],
  computeUnitsUsed: 490
}
```
4. What behavior did you expect?
_Transaction executed successfully_

**Expected behavior**
_Transaction executed successfully_

**Screenshots**

**Hyperledger Solang version**
Version of Solang (e.g. v0.1.13) -- `solang version v0.1.13`

**Include the complete solidity source code**
Please include all the Solidity source so we can reproduce the issue.
```
contract flipper {
    bool private value;

    /// Constructor that initializes the `bool` value to the given `init_value`.
    constructor(bool initvalue) {
        value = initvalue;
    }

    /// A message that can be called on instantiated contracts.
    /// This one flips the value of the stored `bool` from `true`
    /// to `false` and vice versa.
    function flip() public {
        value = !value;
    }

    /// Simply returns the current value of our `bool`.
    function get() public view returns (bool) {
        return value;
    }
}
```
**Additional context**

**Comment by LucasSte** [comment]
Hi @wolfflow, what is the version of `@solana/solidity` you are using?

We have updated the encoding scheme of Solana from the latest Typescript library release and it does not work with Solang 0.1.13.

You can try either installing Solang from sources or using the Typescript library version 0.0.22.

We will release a new version of Solang soon to solve this inconvenience too.
