### ISSUE TITLE
Add `compile` flag for disabling storage getters

### ISSUE THREAD

**Issue by xermicus** [hyperledger/solang#1098]
Having the storage getters in the contract might not be useful or desirable for everyone.

**Comment by seanyoung** [comment]
I imagine the motivation is that on Substrate, you can access storage variables through the UI without calling the getter functions.

If we suppress the generation of storage getters, then:
  - The attribute `public` does nothing on storage variables. Should we warn about that? Or maybe info/debug?
  - How does one contract access a public storage variable of another?
