### ISSUE TITLE
Anchor tooling should have much better Solidity integration

### ISSUE THREAD

**Issue by seanyoung** [hyperledger/solang#1142]
The command line tools `anchor new`, `anchor build`, `anchor test` should work with Solidity.

The anchor workspace in e.g. vscode should work well with Solidity too.

This means solang should be downloaded by avm or solana-install.

**Comment by LucasSte** [comment]
@seanyoung I think this issue is already completed, isn't it?

**Comment by seanyoung** [comment]
Yes, fixed by https://github.com/coral-xyz/anchor/pull/2421
