### ISSUE TITLE
Have to manually set "isSigner" of dataAccount to false in IDL when using PDA storage

### ISSUE THREAD

**Issue by swaglord8** [hyperledger/solang#1184]
I'm new to Solang and Solana development in general so my understanding of high level details might be off.
I'm using a PDA to store data and funds which is derived from two user addresses that should control the funds and data.
From my understanding, if I do this I only need to sign the "new" method transaction with the payer account, and not with a storage account. https://solang.readthedocs.io/en/latest/targets/solana.html#setting-the-payer-seeds-bump-and-space-for-a-contract

However, the generated IDL says "dataAccount" has isSigner set to true, and will result in a client side signature verification error.
If I manually change isSigner to false everything work as expected. Is this expected behavior?

Here's roughly what my contract code looks like:

```
contract shared_account {
  address private user_a;
  address private user_b;

  @space(1337)
  @seed("foo")
  // PDA will be derived from the address of user A and user B
  @seed(abi.encode(_user_a))
  @seed(abi.encode(_user_b))
  @bump(pda_bump)
  @payer(_user_a) // user A will pay for the storage rent
  constructor(
    address _user_a,
    address _user_b,
    uint64 _initial_deposit,
    bytes1 pda_bump
  ) {
    SystemInstruction.transfer(user_a, address(this), _initial_deposit);
    user_a = _user_a;
    user_b = _user_b;
  }

  function deposit(uint64 amount) signer_is_in_account {
    // ...
  }
  
  function withdraw(uint64 amount) signer_is_in_account {
    // ...
  }
}
```

And client:

```
const [pda, bump] = await PublicKey.findProgramAddressSync(
  [
    Buffer.from('foo'),
    userA.publicKey.toBuffer(),
    userB.publicKey.toBuffer(),
  ],
  program.programId,
)

const tx = await program.methods
  .new(
    userA.publicKey,
    userB.publicKey,
    new BN(LAMPORTS_PER_SOL), // funds to deposit
    Buffer.from([bump]),
  )
  .accounts({ dataAccount: pda })
  .transaction()

await provider.sendAndConfirm(tx, [userA])
```

**Comment by seanyoung** [comment]
You are right, if there is a seed then a signer is not required. See https://github.com/hyperledger/solang/pull/1198
