### ISSUE TITLE
Parser fails to recognise `error` identifier

### ISSUE THREAD

**Issue by rkrasiuk** [hyperledger/solang#1193]
**Describe the bug**
Parser fails to recognise `error` identifier. 

**To Reproduce**
`solang-parser = "=0.2.2"`

```rust
let content = r#"
contract Contract {
    function test() internal {
        bytes memory error = bytes("");
        if (error.length > 0) {}
    }
}
"#;
solang_parser::parse(content, 0).expect("can parse");
```

**Expected behavior**
Parser successfully recognizes error identifier.

**Screenshots**
<img width="1253" alt="Screenshot 2023-02-21 at 10 57 29" src="https://user-images.githubusercontent.com/25429261/220296685-2d56525e-7a5e-4eed-bf56-9afa8bd244b6.png">

**Include the complete solidity source code**
Please include all the Solidity source so we can reproduce the issue.
```solidity
contract Contract {
  function test() internal {
    bytes memory error = bytes("");
    if (error.length > 0) {}
  }
}
```

**Additional Context**
https://github.com/foundry-rs/foundry/issues/4403

**Comment by seanyoung** [comment]
Yes, this is a problem. `error` is a keyword in other contexts so this is causing problems. The grammar will need fixing, this will be a tough one. :disappointed:
