### ISSUE TITLE
codegen has Expression::SignedMore and Expression::UnsignedMore but only Expression::MoreEqual

### ISSUE THREAD

**Issue by seanyoung** [hyperledger/solang#1200]
There is no signed/unsigned version of `Expression::MoreEqual` or `Expression::LessEqual`.

I _think_ what happened is that signed/unsigned versions of Less/More were introduced for yul, which has no built for `>=` and `<=`. However, `Expression::SignedMore` and `Expression::UnsignedMore` both switch on the signedness of their first argument.

This would mean that:
- `slt` vs `lt` is not honored in codegen
- It is inconsistent.

Also I am puzzled why evm has `lt` and `gt`:
- Surely they are identical with their arguments swapped. IIRC risc-v isa does not have both
-  Without `lte` and `slte`extra instructions are needed for `a >= b`.

**Comment by LucasSte** [comment]
> This would mean that:
> 
> * `slt` vs `lt` is not honored in codegen
> * It is inconsistent.

What do you mean by not honored in codegen? Everything from the AST to emit is done with signed and unsigned differentiation. We only switch on the sign for the first operand from the AST to CFG.

**Comment by seanyoung** [comment]
How about:

```solidity
function less_signed(uint a, uint b) returns (bool c) {
     asm { c = slt(a, b) }
}
```
So the types of `a` and `b` are unsigned but we do a signed comparison, right?

**Comment by LucasSte** [comment]
> So the types of `a` and `b` are unsigned but we do a signed comparison, right?

Yes. Yul allows many unsafe constructions, including the one you pointed.
The the codegen for YUL goes through another code path, so we do not switch on the sign of the operand, but on the builtin called.

**Comment by seanyoung** [comment]
> Yes. Yul allows many unsafe constructions, including the one you pointed. The the codegen for YUL goes through another code path, so we do not switch on the sign of the operand, but on the builtin called.

You are right, yes this is what happens.

Would it make sense to have `Expression::More` and `Expression::MoreEqual` have an `signed` field and remove the `Expression::SignedMore` and `Expression::UnsignedMore` (and the other comparison operators)? It is a bit messy right now.

**Comment by LucasSte** [comment]
> Would it make sense to have `Expression::More` and `Expression::MoreEqual` have an `signed` field and remove the `Expression::SignedMore` and `Expression::UnsignedMore` (and the other comparison operators)? It is a bit messy right now.

I think that's OK, provided that the CSE operators remain there.
