### ISSUE TITLE
Event not found after importing interface

### ISSUE THREAD

**Issue by andywer** [hyperledger/solang#1234]
**Describe the bug**
Assume a contract C implementing an interface I that's been imported from another file. I declares an event, C emits it. Try to compile for Substrate.

solc: Works
solang: `event 'MyEvent' not found`

**To Reproduce**
See <https://github.com/0xamberhq/solang-issues/tree/main/01-emit-iface-events>.

**Expected behavior**
Should compile without errors.

**Hyperledger Solang version**
Solang v0.2.2

**Include the complete solidity source code**
See <https://github.com/0xamberhq/solang-issues/tree/main/01-emit-iface-events>.

**Additional context**
Seems to fail only when naming the symbols to import (`import {X} from "./X.sol";` vs `import "./X.sol";`).

**Comment by xermicus** [comment]
No worries :rocket:
