### ISSUE TITLE
Error: Permission denied @ dir_s_mkdir - /usr/local/Caskroom/solang. Permission denied @ rb_sysopen 

### ISSUE THREAD

**Issue by ltfschoen** [hyperledger/solang#1346]
**Describe the bug**
When I tried to install Solang on my macOS by following the README instructions and running:
```
brew install hyperledger/solang/solang
```
It gave me an errors like `Error: Permission denied @ dir_s_mkdir - /usr/local/Caskroom/solang` and `Permission denied @ rb_sysopen`, since you can't run `sudo brew ..`

To solve it I had to first run `sudo chown -R $(whoami) /usr/local/Caskroom/solang`
and then run `brew install --cask hyperledger/solang/solang`
So suggest updating the README to mention how to set permissions due to the Homebrew restriction.

**To Reproduce**
1. Use a macOS machine not as root
2. Run `brew install --cask hyperledger/solang/solang`
3. Encounter permissions errors

**Expected behavior**
The README instructions should also help users set permissions if the tools restrict usage with sudo

**Comment by LucasSte** [comment]
We can point your solution in our documentation, but I do not think this is an issue with on our end. Many users reported the permission denied problem when installing other casks and formulae. There is even a Gist for this fix: https://gist.github.com/irazasyed/7732946

From what I've read, another program might have altered the permissions in your brew folder, so you needed to give permissions to your user on MacOS again.

@seanyoung and @xermicus Any thoughts on this issue? Should we include a link to the gist?

**Comment by xermicus** [comment]
I can't repro as I'm not developing on mac OS. But if this issue is not specific to our project I agree with @LucasSte. We can and should not fix this.

>  Should we include a link to the gist?

Is this error the "normal" case if you try to install solang via brew? If it is the norm, we should add the link or even better have fully working instructions. If this is not the norm (e.g. it does only occur under specific conditions that do not represent the majority of users) I don't see why we should do that.

**Comment by LucasSte** [comment]
> Is this error the "normal" case if you try to install solang via brew? If it is the norm, we should add the link or even better have fully working instructions. If this is not the norm (e.g. it does only occur under specific conditions that do not represent the majority of users) I don't see why we should do that.

I have a Mac desktop and a Mac laptop and I have never had that error. I think @seanyoung also tested the Brew command on a Mac laptop and did not have any problem.

**Comment by ltfschoen** [comment]
yes i think this is isolated to just my machine. i had the same error reinstalling docker with brew
```
==> Purging files for version 4.15.0,93002 of Cask docker
Error: Permission denied @ dir_s_mkdir - /usr/local/Caskroom/docker
```
so happy to close the issue, but like you mentioned it would be great if there was a tooltip in the setup guide

**Comment by LucasSte** [comment]
I'm closing this issue, as it is not related to our repository.
