### ISSUE TITLE
error: failed to select a version for `ink_env`

### ISSUE THREAD

**Issue by ltfschoen** [hyperledger/solang#1351]
**Describe the bug**

The crate dependencies https://crates.io/crates/solang/0.3.0/dependencies list `=4.1.0` `ink_env` as a dependency at that link. But if i clone the latest version of this repo, it's Cargo.toml file says it uses `ink_env` "=4.2.0"`.

I tried to import that 'solang' crate as a dependency into another project's called 'cargo-contract' v3.0.1, which has a Cargo.toml file with  `solang = { version = "^0.3.0" }`, and that project uses `ink_env = "4.2.0"`.
but when i try to compile that 'cargo-contract' v3.0.1 project, it gives me error:
```bash
error: failed to select a version for `ink_env`.
    ... required by package `solang v0.3.0`
    ... which satisfies dependency `solang = "^0.3.0"` of package `cargo-contract v3.0.1 (/Users/me/cargo-contract/crates/cargo-contract)`
versions that meet the requirements `=4.1.0` are: 4.1.0

all possible versions conflict with previously selected packages.

  previously selected package `ink_env v4.2.0`
    ... which satisfies dependency `ink_env = "^4.2.0"` of package `contract-transcode v3.0.1 (/Users/me/cargo-contract/crates/transcode)`
    ... which satisfies path dependency `contract-transcode` (locked to 3.0.1) of package `cargo-contract v3.0.1 (/Users/me/cargo-contract/crates/cargo-contract)`

failed to select a version for `ink_env` which could resolve this conflict
```

I referred the matter to the Rust community on Discord, and @kpreid informed me that the the dependency at crates.io https://docs.rs/crate/solang/latest/source/Cargo.toml.orig is infact "=4.1.0", and they pointed out that this is the reason why using ` = ` version dependencies is not recommended, since you can never use libraries that have conflicting `=` dependencies, and they suggested that if a library routinely needs to use exact version `=` to work then there may be a semver concern.

I think it may be necessary to find/replace `=4.2.0` with just `4.2.0`

**To Reproduce**
1. Clone cargo-contract repo version 3.0.1
2. Update its Cargo.toml file and add dependency `solang = { version = "^0.3.0" }`
3. Build it to generate the error `cargo build`

**Expected behavior**
No error 

**Screenshots**

**Hyperledger Solang version**
Solang v0.3.0

**Include the complete solidity source code**
N/A

**Additional context**

Relates to me trying to tackle this task https://github.com/paritytech/cargo-contract/pull/1137

**Comment by xermicus** [comment]
Thanks for bringing this up. I pinned the ink dependencies because they might require newer Rust version with new minor releases, which broke our builds in the past. I don't know if this is semver compliant or not, [it's unclear](https://www.reddit.com/r/rust/comments/rtp3yg/is_rust_compiler_version_dependency_update_a/). And since solang is a binary crate not (yet) intended to be used as a library itself, I didn't think that this is a problem. However, given this should be a rare occurrence, it should not be necessary.
