### ISSUE TITLE
Solang emits invalid code when using modifiers (Substrate)

### ISSUE THREAD

**Issue by TorstenStueber** [hyperledger/solang#1385]
There seems to be a bug in the code emission for Substrate when using a modifier. I could reduce it to the following minimal example:

```
//SPDX-License-Identifier: UNLICENSED
pragma solidity 0.8.20;

contract TestContract {

    modifier testModifier() {
        _;
    }

    event TestEvent(uint number);

    function testMethod()
        external
        testModifier
    {
        emit TestEvent(2**256-1);
    }
}
```

When compiling for Substrate and instantiating and calling the method `testMethod`, then the contract traps although it should run without problems.

What is very mysterious here is that the contract will not trap and execute successfully if I change the file either one of the following ways:

- either remove the `testModifier` from `testMethod`
- or change the number emitted in the `testEvent` from `2**256-1` to, e.g., `2**255-1`

## Version
I used `solang version v0.3.0`

**Comment by TorstenStueber** [comment]
By the way, the result (and error) is exactly the same whether using `wasm-opt` after compilation or not.

**Comment by xermicus** [comment]
The bug is that with the modifier, the function body does not go through constant folding, causing an overflow at runtime (the overflow without compile time constant folding is expected; if you remove the modifier but also use `--no-constant-folding` you have the same outcome).

**Comment by xermicus** [comment]
Another interesting observation pointed out by @TorstenStueber is that this modifier won't get optimized away - even if it does nothing. Maybe LLVM or wasm-opt catches this up, but in our cfg it's still there, basically as a useless trampoline:

```
# function TestContract::TestContract::testMethod::modifier0::testModifier public:true selector:b9c3d0a5 nonpayable:true
# params: 
# returns: 
block0: # entry
         = call TestContract::TestContract::function::testMethod 
        return 

# function TestContract::TestContract::function::testMethod public:false selector:b9c3d0a5 nonpayable:true
# params: 
# returns: 
block0: # entry
        ty:uint256 %temp.0 = ((uint256 2 ** uint256 256) - uint256 1)
        ty:bytes %abi_encoded.temp.1 = (alloc bytes len (uint32 1 + uint32 32))
        writebuffer buffer:%abi_encoded.temp.1 offset:uint32 0 value:uint8 0
        writebuffer buffer:%abi_encoded.temp.1 offset:(uint32 0 + uint32 1) value:%temp.0
        emit event TestContract.TestEvent topics (alloc slice uint8 uint32 32 "\0TestContract::TestEvent\0\0\0\0\0\0\0\0") data %abi_encoded.temp.1 
        return

(dispatcher will call into the modifier)
```

**Comment by TorstenStueber** [comment]
So that means that for now we can avoid this problem by replacing `2**256-1` by `2**255-1 + 2**255`? At least that works.
