### ISSUE TITLE
Rename Substrate to Polkadot

### ISSUE THREAD

**Issue by xermicus** [hyperledger/solang#1398]
I'm thinking about renaming the Substrate target to Polkadot.

* Polkadot is a much stronger brand than Substrate. I don't have evidence for this, but I'd bet that way more people (especially not very into the Polkadot ecosystem, which part of our target audience) know the term Polkadot than Substrate.
* The contracts pallet can be seen as "Polkadots native contracts"
* Substrate is a dying brand (the brand, not the technology). Chances are that it'll just be something like "[Polkadot SDK](https://forum.polkadot.network/t/psa-parity-is-currently-working-on-merging-the-polkadot-stack-repositories-into-one-single-repository/2883/13)" or something similar in the future anyways.
* Highly unlikely that there will be multiple popular contract runtimes, which we'd both support, in the foreseeable future.
* The Solana backend is also just called Solana and not sealevel or SPL or anchor or SBF

**Comment by seanyoung** [comment]
Any rename should be complete, including file names/paths

**Comment by xermicus** [comment]
Yes you are absolutely right; didn't write that explicitly but its what I meant. It's not just about renaming the target in the CLI, but consistently switching out these two terms everywhere.
* Source code, including tests
* File names, paths, etc
* Occurances in the CLI and config TOML
* Documentation
* [This repo](https://github.com/hyperledger/solang-substrate-ci) comes to my mind, but not sure if that's worth the struggle (after all it's a fork of the _substrate_\_contracts_node

However, we should be careful with a blind search and replace, as there might be specific occurances where "Substrate" is still the correct term to use.

**Comment by seanyoung** [comment]
The builtin import `import "substrate";` will also need to be renamed. I think we should do this rename sooner rather than later, to reduce user pain.

**Comment by Harsh06-afk** [comment]
Hey there,
I would like to work on this issue, can you provide me with some more references to start with.
I would like to join community can you provide relevant links.

**Comment by xermicus** [comment]
> Hey there, I would like to work on this issue, can you provide me with some more references to start with. I would like to join community can you provide relevant links.

https://discord.gg/hyperledger

I think this needs some coordination. It involves changing a bunch of things out of the scope of PRs. Also it'll require a massive PR changing many lines, causing many conflicts if not merged timely.
