### ISSUE TITLE
Is there any way to modify the writable data account provided by users?

### ISSUE THREAD

**Issue by YanhuiJessica** [hyperledger/solang#1489]
In native Solana program, the program can write data into the account after invoking `system_instruction::create_account`.

The `data` field of `AccountInfo` can be modified, according to the [document](https://solang.readthedocs.io/en/latest/targets/solana.html#builtin-accountinfo).
But I got `error: struct 'AccountInfo' field 'data' is readonly` when I tried to assign value to `tx.accounts[i].data`.

**Comment by seanyoung** [comment]
@LucasSte has this been fixed in main?

**Comment by LucasSte** [comment]
> @LucasSte has this been fixed in main?

No, it is not. I'm fixing now.
