### ISSUE TITLE
Semi-incorrect `New` expression parsing

### ISSUE THREAD

**Issue by brockelmore** [hyperledger/solang#1550]
**Describe the bug**
Solidity has a `new` keyword, used like `new Contract()`. Solang parses this as `Expression::New(Loc, Box<Expression>)`, and from what I can tell, it always is `Expression::New(Loc, Expression::FunctionCall(...))`. This is slightly incorrect (but can be worked around) - it should be `Expression::New{loc: Loc, type: Box<Expression>, inputs: Vec<Expression>}`.

You can see that this is the correct parsing here: https://github.com/ethereum/solidity/blob/cc7a14a61d13cf62211d0d482a6529eab1413ab3/libsolidity/ast/AST.h#L2238-L2242

Basically, the function call is to `new`, not the identifier/type name.

Disconnecting the `new` and the `type` makes it harder to disambiguate. Take:
```solidity
function createOrConstruct(address x) public {
    // Expression::New(loc, Expression::FunctionCall(Expression::Variable(Identifier { name: "Other", .. }), [Variable(Identifier { name: "x", .. })]))
    Other a = new Other(x);
    // vs: Expression::FunctionCall(Expression::Variable(Identifier { name: "Other", .. }), [Variable(Identifier { name: "x", .. })])
    Other b = Other(x);
}

contract Other {
    constructor(address) {}
}
```

You can see that you actually have to carry the `new` modifier forward in some capacity, as opposed to if it were the proposed structure.

I believe disambiguation is always possible still, but it feels error prone or requires extra work to disambiguate (and wouldn't actually surprise me if there were a bug in there because of this).

**Expected behavior**
The structure of `Expression::New` to be `Expression::New{loc: Loc, type: Box<Expression>, inputs: Vec<Expression>}`

**Hyperledger Solang version**
solang-parser v0.2.4 (but also 0.3.2)

**Include the complete solidity source code**
See above

**Comment by seanyoung** [comment]
`new` parsing is tricky. There are three basic forms:

```
(new D{value: 1})();
(new D){value: 1}();
new D{value: 1}();
```

All of these produce different parse trees. Our lalrpop grammar has to be unambiguous, so this is what the grammar produces. 

We could walk the tree and re-arrange the parse tree to your liking, but note that the parse tree is used be e.g. `forge-fmt` to write out re-formatted Solidity, so it has to be representative. I am not sure it is worthwhile. Our parse tree does not have to be the same as the solc version.

What are you trying to do with the solang-parser parse tree?

**Comment by brockelmore** [comment]
That makes sense - I am using it for github.com/nascentxyz/pyrometer

Basically abstract interpretation/bound analysis for security analysis. 

Feel free to close - it’s not a big deal just felt wrong and wanted to flag it
