### ISSUE TITLE
Conversion of payable

### ISSUE THREAD

**Issue by curry68** [hyperledger/solang#1614]
function flip(address _addr) public payable {
            total += 1;
            payable(_addr).transfer(1);
    }
How to call this in Solana：
    await program.methods
      .flip(transferToAccount)
      .accounts({ dataAccount: dataAccount.publicKey})
      .rpc();
Isn’t this right? How can I transfer the sol into the contract?thanks

**Comment by seanyoung** [comment]
A transfer needs to transfer tokens from somewhere to somewhere else. You can't magic tokens out of nowhere.

You can use airdrop or other Solana methods of funding accounts.
