### ISSUE TITLE
Unable to make stdlib

### ISSUE THREAD

**Issue by spino17** [hyperledger/solang#1653]
I tried running `make` in `stdlib` as mentioned in #1652. Getting the following error:
```clang -c --target=sbf -emit-llvm -O3 -ffreestanding -fno-builtin -Wall -Wno-unused-function -Xclang -fexperimental-max-bitint-width=512 solana.c -o ../target/bpf/solana.bc
error: unknown target triple 'sbf', please use -triple or -arch
make: *** [../target/bpf/solana.bc] Error 1```

**Comment by seanyoung** [comment]
You need to use the llvm build with includes our changes,see https://solang.readthedocs.io/en/v0.3.3/installing.html#step-1-install-the-llvm-libraries

**Comment by spino17** [comment]
I did used that, still the same issue is coming! @seanyoung
