### ISSUE TITLE
Solang needs a logo

### ISSUE THREAD

**Issue by seanyoung** [hyperledger/solang#362]
We don't have a logo. This would be nice for e.g. the vscode extension.

I think some sort of animal would be great, something like a crocodile or a manatee. Or something inspired by Pegbiter https://monkeyisland.fandom.com/wiki/Pegbiter

The logo should be svg, open source, and most of all cute.

**Comment by Hyperion101010** [comment]
:+1:  If anyone is interested you can follow few guidelines laid out for open source logos
here https://opensourcedesign.net/

**Comment by LucasSte** [comment]
A logo is already available.
