### ISSUE TITLE
Now we can generate eWASM smart contracts from EVM bytecode

### ISSUE THREAD

**Issue by Kenun99** [hyperledger/solang#658]
I implement an EVM-to-eWASM bytecode translator that can ensure the fidelity of translation. EVM bytecode contracts now can run in eWASM runtime directly. I also build a local blockchain and test the eWASM contracts. The results look nice. It is surprise that we can generate accurate LLVM bitcode even we do not have source code. 
Check [https://github.com/Kenun99/ethsema](https://github.com/Kenun99/ethsema) for more details.

**Comment by Kenun99** [comment]
https://github.com/ethsema/ethsema-paper

**Comment by drewstone** [comment]
Is there a link to an implementation?
