### ISSUE TITLE
msg.sender provides wrong AccountId on substrate

### ISSUE THREAD

**Issue by h4nsu** [hyperledger/solang#679]
(seems to me like this could be related to #666)

I'm using solang 0.1.9 installed via cargo from crates.io and a custom substrate node (https://github.com/Cardinal-Cryptography/aleph-node/tree/smartnet) which is based on substrate 4.0.0-dev. It looks like `msg.sender` is providing an incorrect value. This is my minimal example:
```
contract mytoken {
    function test(address account, bool sender) public view returns (address) {
        if (sender) {
            return msg.sender;
        }
        return account;
    }
}
```
When I call that function from some address and provide the same address as the `account` parameter, I'm getting two different values when switching the bool parameter:

![image](https://user-images.githubusercontent.com/9969515/155400749-133514bb-e67b-42e0-bf4d-d58e62092687.png)

**Comment by LucasSte** [comment]
Hi @h4nsu ,
Please check [this](https://github.com/hyperledger-labs/solang/pull/682) PR. I added your example contract to our mock VM for Substrate test and our integration tests with Substrate. Everything seems to be working as expected.

I also tested your contract on Substrate's interface and see that the returned addresses aren't equal. Perhaps, this is a issue with Substrate's UI interface. Did you experience `msg.sender` returning the incorrect address in any other circumstances?

**Comment by LucasSte** [comment]
Hello @h4nsu,
I added the tests you suggested [here](https://github.com/hyperledger-labs/solang/pull/690). Our CI tests passes as well.
Do you have any suggestion of integration tests we should be testing to recreate your issue?
Integration tests deploy a Solang compiled contract into Substrate and allow us to call its methods. Have a look at the test I added for your issue on my last PR:
https://github.com/hyperledger-labs/solang/blob/main/integration/substrate/msg_sender.spec.ts#L7

**Comment by extraymond** [comment]
@LucasSte 
I think it might possible pallet-contract now takes a salt argument. And the integration test uses old pallet-contract code, which didn't have that as a option, also the polkadot-js api used in integration tests didn't take that salt argument either.

This is my related substrate so issue.
https://substrate.stackexchange.com/questions/714/cross-contract-call-failure-when-using-different-salt-to-instantiate-contract

As you can see, the address generated with different salt argument ends up having different behavior.

**Comment by seanyoung** [comment]
@extraymond this issue here does not use the instantiate contract api call.

**Comment by extraymond** [comment]
@seanyoung Ah! I mistakenly remember this issue being the one related to issue666. I'll move my comment there!

**Comment by xermicus** [comment]
This has been fixed a while ago.
