### ISSUE TITLE
Make Solang compiled contracts compatible with Anchor

### ISSUE THREAD

**Issue by seanyoung** [hyperledger/solang#964]
Remaining work (who is working on it in parenthesis)

- [x] Borsh decoding (Lucas)
- [x] Allow function selector to be overriden with new selector, variable length on Solana. (Sean)
- [x] Convert IDL file to solidity interface file `solana metadata --target solana [-o outputfile] foo.idl` (Sean)
- [x] Use borsh encoding for function arguments calls with overriden selector (provide end to end IDL tests with this) (Sean)
- [x] Use borsh encoding for events (Lucas)
- [x] Use borsh encoding for function return values with overriden selector (Sean)
- [x] #1030
- [x] #1040
- [x] Do not pass destination/sender account via input, but via accounts
- [x] Solang should produce one binary per contract, just like Anchor/Substrate/ewasm (Sean)
- [x] Anchor IDL should support 256-bit integers
- [x] Custom width integers should be fixed for Anchor IDL (either disabled or rounded to the next existing width)
- [x] Produce IDL for Solana contracts
- [x] `abi.encode()` and `abi.decode()` should use borsh encoding (Lucas)
- [x] Use borsh encoding for `Insert::AssertFailure`
- [x] Update documentation for `try ... catch`

**Comment by LucasSte** [comment]
It is not on this list, but many instructions utilize ABI encoding and need to be modified. One example is `Instr::AssertFailure`. Its arguments are ABI encoded in `emit`. That must change if we migrate to Borsh on Solana.

**Comment by seanyoung** [comment]
Note that `try .. catch` also uses abi encoding/decoding but this functionality does not work on Solana anyway. This needs clearer compiler error messages and documentation.
