### ISSUE TITLE
Milestone 3. Events with indexed fields are not encoded correctly

### ISSUE THREAD

**Issue by xermicus** [hyperledger/solang#970]
If an event has fields declared indexed, they should be passed into the Substrate topics. This is not implemented correctly today. Ensure that indexed fields are passed into topics and add an integration test for this at

https://github.com/hyperledger-labs/solang/tree/main/integration/substrate

Success means that a pull request has had all its review comments addressed and it is merged.

**Comment by xermicus** [comment]
> This is not implemented correctly today. 

@seanyoung before I start digging here, can you remember some more insights or hints on this one?

**Comment by seanyoung** [comment]
I recall that there are a few issues.
- Substrate requires topic values to be unique, and solang does not enforce this
- The code gen in src/emit/ is not correct, and sometimes event emitting does not work at all (unfortunately I don't have a test case)
- I don't think the semantics of events on Solidity and Substrate/Ink! match properly
