### ISSUE TITLE
Solang compiled contracts must work with Solana v1.11

### ISSUE THREAD

**Issue by LucasSte** [hyperledger/solang#991]
As Solana migrated to a new API for system calls, Solang compiled contracts do not work with its virtual machine anymore.

- [ ] Remove `sol_alloc_free_` syscall usage (not longer exists)

**Comment by seanyoung** [comment]
I've started work on the 2nd item. I think the first item needs to be done first though, so I've started on that now.

**Comment by seanyoung** [comment]
The aim solana v1.11 compatibility. For that, only the heap changes are needed
